databases:
  - name: medlab-db
    plan: free
    databaseName: medlab

services:
  - type: web
    name: medlab-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: ConnectionStrings__Default
        fromDatabase:
          name: medlab-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: static
    name: medlab-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/medlab-ainsights/browser
    rootDir: ./frontend
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
